version: '3.8'
#segue la lista dei servizi
services:
    server_p:
      ports:
        - 8085:8085
      depends_on:
        - server_p

    postgres:
      environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: cielo

      volumes: localdatabase:/data/db  #RIVEDERE I DATI DA PRENDERE

      ports: "5433:5432"

volumes:
  localdatabase:
  
networks:
  composenetwork:
    driver: bridge